# Inspired by https://github.com/PaulJuliusMartinez/jless/blob/main/.github/workflows/release.yml

name: release
on:
  push:
    # Enable testing on branches
    # branches:
    #   - test-release
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-binaries:
    name: create-binaries
    strategy:
      matrix:
        platform:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu  }
          - { os: macos-latest , target: x86_64-apple-darwin       }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.platform.target }}
          #components: clippy, rustfmt
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target=${{ matrix.platform.target }}
      - name: Strip binary
        run: strip target/${{ matrix.platform.target }}/release/fix-iso-dates
      - name: Compress binary
        run: |
          mv target/${{ matrix.platform.target }}/release/fix-iso-dates ./
          zip -X fix-iso-dates-${{ matrix.platform.target }}.zip fix-iso-dates
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fix-iso-dates-${{ matrix.platform.target }}.zip
          path: fix-iso-dates-${{ matrix.platform.target }}.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
